bame: "Post Test"
runs:
  using: "composite"
  steps:
    - name: Extension checks
      run: |
        jupyter server extension list 2>&1 | grep -ie "jupyterlab_reana.*OK"
        jupyter labextension list 2>&1 | grep -ie "jupyterlab_reana.*OK"
      shell: bash
    - name: Browser check
      run: python -m jupyterlab.browser_check
      shell: bash