name: Install dependencies and build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: "Base Setup: Node + Python"
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt
    
    - name: Install JS dependencies
      run: YARN_ENABLE_IMMUTABLE_INSTALLS=false jlpm

    - name: Test the extension
      run: |
        set -eux
        jlpm run test

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

        jupyter serverextension enable --py jupyterlab_reana
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "jupyterlab_reana.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "jupyterlab_reana" jupyterlab