name: Test

on:
  push:
    branches: main
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/test
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: ./.github/actions/build-ext
      - uses: ./.github/actions/post-test