name: Test

on:
  push:
    branches: main
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python_version }}
      - uses: ./.github/actions/test
      
      - name: Upload results to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: ./.github/actions/build-ext
      - uses: ./.github/actions/post-test